tasks:
  - name: dfx dev
    init: |
      sudo apt-get update && export DEBIAN_FRONTEND=noninteractive \
      && apt-get -y install \
      liblmdb-dev \
      # cpp \
      # gcc-8-multilib \
      # libgcc-8-dev \
      gcc \
      # g++ \
      build-essential \
      gdb \
      python3-pip \
      make \
      cmake \
      pkg-config \
      gcc-multilib \
      && apt-get clean

      pip3 install pipenv && \
      pip3 install pre-commit

      rustup toolchain install stable && \
      rustup target add wasm32-unknown-unknown --toolchain stable

      curl -fsSL https://sdk.dfinity.org/install.sh | bash -s -- -y
      echo 'export PATH="$PATH:$HOME/bin"' >> "$HOME/.bashrc"
      . "$HOME/.bashrc"
      dfx --version

      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash && \
      . ~/.bashrc && \
      nvm i 16 && \
      npm i -g typescript && \
      npm i -g ts-node

      cargo install ic-cdk-optimizer && \
      cargo install cargo-audit && \
      cargo install cargo-nextest && \
      cargo install cargo-llvm-cov

      cd src
      ./sh_post_container_created.sh

      dfx start --background
      ./sh_reinstall.sh
      dfx stop

    command: |
      cd src
      curl -fsSL https://sdk.dfinity.org/install.sh | bash -s -- -y
      echo 'export PATH="$PATH:$HOME/bin"' >> "$HOME/.bashrc"
      . "$HOME/.bashrc"
      dfx --version
      ./sh_setup_dev.sh
      ./start.sh
vscode:
  extensions:
    - matklad.rust-analyzer
jetbrains:
  pycharm:
    plugins:
      - org.rust.lang
      - ru.adelf.idea.dotenv
      - com.chrisrm.idea.MaterialThemeUI
      - com.mallowigi
